### PR TITLE
Disable the Hydrate task on client only configs

### LINKED ISSUE #57: Hydrate is run when only client tasks are allowed
We're using the [`allowedGroups`](https://github.com/atlassian-labs/storybook-addon-performance#usage-filtering-task-groups) filter to run the addon only on the client, because SSR tasks are failing on production builds.

Screenshot 2020-11-13 at 11 30 25

The PR for this feature (#40) intended to disable Hydrate (which depends on SSR) for client only configs, however, Hydrate is always ran:

Screenshot 2020-11-13 at 15 06 30

(☝️ the Hydrate task should not be run here)

[Reproduce this on the example Storybook](https://storybook-addon-performance.netlify.app/?path=/story/examples--only-client-performance)

### PR DESCRIPTION
**Pull request by robinmetral**
Closes #57 

There are obviously several ways to do this. I chose not to do it in `preset/client.tsx` because it would have required to export a function (taking an allowedGroups param) instead of an object (which is the current export in both the client and server presets).

I think that filtering the tasks in get-groups is a good option because the allowedGroups is already in use there, but I realise that this introduces some extra complexity (it will break if we change the Hydrate task's name).

Happy to take any feedback!

### CODE REVIEW

**Comment by DarkPurple141** [comment]
Some initial thoughts here: Can we add a test for this - particularly with the hardcoded 'Hydrate'. These could potentially be better typed across the codebase as keys to facilitate this kind of behaviour in a smoother more typesafe way. Thanks for the contribution!

**Comment by robinmetral** [comment]
Hi @DarkPurple141, sorry for my late reply and thanks for your feedback!

Totally agree this would be good to test. I've covered this as part of the group filtering spec, I think this is where it makes the most sense. Let me know what you think!

**Comment by alexreardon** [comment]
This is an interesting one for sure. A 'hydrate' task does not make sense when there is no 'server' component, as hydrate requires SSR to work. Hydrate seems to straddle the line between client and server.

File: src/tasks/get-groups.ts [hunk 1]
```diff
@@ -31,7 +31,13 @@ export function getGroups({
     result.push(server);
   }
   if (allowedGroups.includes('client')) {
-    result.push(client);
+    const tasks = allowedGroups.includes('server')
```
Comment (alexreardon) [inline src/tasks/get-groups.ts:34]: This seems brittle to me - what if we changed the task name in the future?

File: test/panel/group-filtering.spec.tsx [hunk 2]
```diff
@@ -15,7 +15,7 @@ import server from '../../src/tasks/preset/server';
 it('should allow filtering of tasks (client only)', () => {
   // 1: Initial render
   const channel: Channel = new Channel({ async: false });
-  const { container, queryByText } = render(
+  const { container, queryByText, debug } = render(
```
Comment (alexreardon) [inline test/panel/group-filtering.spec.tsx:18]: I don't think `debug` is needed now

**Review by alexreardon — COMMENTED** [review]
I am unsure if this is the best way to achieve this behaviour. I don't know exactly what the 'best way' would be right now

**Comment by alexreardon** [comment]
Hydrate is not a client task: it requires `renderToString`
Hydrate is not a server task: it requires client side `ReactDOM.hydrate`

🤔

File: src/tasks/get-groups.ts (hunk 1 above)
Comment (alexreardon) [reply src/tasks/get-groups.ts:34]: In order to allow `hydrate` both `server` and `client` needs to be in the allowed groups

**Review by alexreardon — CHANGES_REQUESTED** [review]

**Comment by alexreardon** [comment]
Perhaps a string match on the task name "hydrate" is the best we can do for now...

File: src/tasks/get-groups.ts (hunk 1 above)
Comment (alexreardon) [reply src/tasks/get-groups.ts:34]: Oh I see, this condition is inside a block that is checking for `client` and `server`

Can we add a comment to the code explaining that `hydrate` can only be run if both `client` and `server` is allowed?

**Comment by alexreardon** [comment]
I think the string matching on the task name is the best we can do at this stage without much larger changes. Only minor changes left then:

- add a small comment to the code explaining why the hydrate task is being excluded from `client` tasks when `server` is not an allowed group
- remove `debug` from the test file

**Comment by alexreardon** [comment]
Thanks for your work on this @robinmetral!! ❤️

**Comment by AndrewOCC** [comment]
I've merged this PR and will raise another one to make these minor changes – thanks @robinmetral 🎉

File: test/panel/group-filtering.spec.tsx (hunk 2 above)
Comment (robinmetral) [reply test/panel/group-filtering.spec.tsx:18]: Sorry about this, my editor probably forgot to warn me about it

**Comment by robinmetral** [comment]
Thanks everyone, sorry I couldn't address the last small comments before the merge, the discussion happened in the middle of the night for 🙈

Thank you for picking it up @AndrewOCC, and thanks again for the great tool!
